spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heima
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#这是配置数据库表的前缀，默认的是book
#mybatis-plus:
#  global-config:
#    db-config:
#      table-prefix: tb_


